namespace DBADashWebView;

/// <summary>
/// Curated map of Windows DBADashGUI areas → same dbo.* procedures the WinForms app calls.
/// Used by GET /api/repository/parity-catalog; all Procedure values must stay on <see cref="DbaDashProcedureBridge"/> allow-lists.
/// </summary>
public static class DbaDashParityCatalog
{
    public sealed record Entry(
        string Category,
        string Label,
        string Procedure,
        bool AddEmptyDayHourTvp,
        int SuggestedTimeoutSeconds,
        string? InstanceParameterName,
        string? DatabaseParameterName,
        string? Notes);

    public static readonly Entry[] Entries =
    [
        new("Summary & checks", "Summary row (all health columns)", "dbo.Summary_Get", false, 60, "@InstanceID", null, null),
        new("Summary & checks", "Offline instance timeline", "dbo.OfflineInstanceTimeline_Get", false, 120, "@InstanceID", null, null),
        new("Summary & checks", "Corruption", "dbo.Corruption_Get", false, 120, "@InstanceID", null, null),
        new("Summary & checks", "Last good CHECKDB", "dbo.LastGoodCheckDB_Get", false, 120, "@InstanceID", null, null),
        new("Summary & checks", "OS loaded module summary", "dbo.OSLoadedModuleSummary_Get", false, 120, "@InstanceID", null, null),
        new("Summary & checks", "OS loaded modules", "dbo.OSLoadedModules_Get", false, 120, "@InstanceID", null, null),
        new("Summary & checks", "OS loaded module status config", "dbo.OSLoadedModulesStatus_Get", false, 120, null, null, "Often repository-wide; add parameters in JSON if required."),
        new("Summary & checks", "Memory dump thresholds", "dbo.MemoryDumpThresholds_Get", false, 60, "@InstanceID", null, null),
        new("Summary & checks", "Backup thresholds", "dbo.BackupThresholds_Get", false, 60, "@InstanceID", null, null),
        new("Summary & checks", "Instance uptime thresholds", "dbo.InstanceUptimeThresholds_Get", false, 60, "@InstanceID", null, null),
        new("Summary & checks", "Collection dates", "dbo.CollectionDates_Get", false, 120, "@InstanceID", null, null),
        new("Summary & checks", "Collection error log", "dbo.CollectionErrorLog_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "CPU", "dbo.CPU_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Performance summary", "dbo.PerformanceSummary_Get", false, 180, "@InstanceID", null, null),
        new("Performance", "Performance counter summary", "dbo.PerformanceCounterSummary_Get", false, 180, "@InstanceID", null, null),
        new("Performance", "Performance counter raw", "dbo.PerformanceCounter_Get", false, 120, "@InstanceID", null, "Add counter keys in extra JSON per GUI."),
        new("Performance", "IO summary", "dbo.IOSummary_Get", false, 180, "@InstanceID", null, null),
        new("Performance", "Waits (detail)", "dbo.Waits_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Waits summary", "dbo.WaitsSummary_Get", true, 180, "@InstanceID", null, "Uses empty @DaysOfWeek/@Hours TVPs when enabled."),
        new("Performance", "Blocking snapshots", "dbo.BlockingSnapshots_Get", true, 180, "@InstanceID", null, null),
        new("Performance", "Running queries — server summary", "dbo.RunningQueriesServerSummary_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Running queries — summary", "dbo.RunningQueriesSummary_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Session waits", "dbo.SessionWaits_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Session waits summary", "dbo.SessionWaitsSummary_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Slow queries — summary", "dbo.SlowQueriesSummary_Get", false, 180, "@InstanceID", null, null),
        new("Performance", "Slow queries — detail", "dbo.SlowQueriesDetail_Get", false, 180, "@InstanceID", null, null),
        new("Performance", "Object execution stats", "dbo.ObjectExecutionStats_Get", false, 180, "@InstanceID", null, "Often needs DatabaseID in JSON."),
        new("Performance", "Object execution stats summary", "dbo.ObjectExecutionStatsSummary_Get", false, 300, "@InstanceID", null, null),
        new("Performance", "Memory usage", "dbo.MemoryUsage_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Memory clerks", "dbo.MemoryClerkUsage_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Memory config", "dbo.MemoryConfig_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Memory counters", "dbo.MemoryCounters_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Query Store options", "dbo.DatabaseQueryStoreOptions_Get", false, 120, "@InstanceID", "@DatabaseID", null),
        new("Performance", "Query Store options summary", "dbo.DatabaseQueryStoreOptionsSummary_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Plan forcing log", "dbo.PlanForcingLog_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Query plan XML", "dbo.QueryPlan_Get", false, 120, "@InstanceID", null, "Binary/XML returned as base64 in grid."),
        new("Performance", "Resource Governor — config", "dbo.ResourceGovernorConfiguration_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Resource Governor — config history", "dbo.ResourceGovernorConfigurationHistory_Get", false, 120, "@InstanceID", null, null),
        new("Performance", "Resource Governor — pools", "dbo.ResourceGovernorResourcePools_Get", false, 180, "@InstanceID", null, null),
        new("Performance", "Resource Governor — pool metrics", "dbo.ResourceGovernorResourcePoolsMetrics_Get", false, 180, "@InstanceID", null, null),
        new("Performance", "Resource Governor — workload groups", "dbo.ResourceGovernorWorkloadGroups_Get", false, 180, "@InstanceID", null, null),
        new("Performance", "Resource Governor — WG metrics", "dbo.ResourceGovernorWorkloadGroupsMetrics_Get", false, 180, "@InstanceID", null, null),
        new("Azure", "Azure DB resource governance", "dbo.AzureDBResourceGovernance_Get", false, 120, "@InstanceID", null, null),
        new("Azure", "Azure DB performance summary", "dbo.AzureDBPerformanceSummary_Get", false, 120, "@InstanceID", null, null),
        new("Azure", "Azure DB pool summary", "dbo.AzureDBPoolSummary_Get", false, 120, "@InstanceID", null, null),
        new("Jobs & SQL Agent", "Jobs list", "dbo.Jobs_Get", false, 120, "@InstanceID", null, null),
        new("Jobs & SQL Agent", "Agent jobs (GUI grid)", "dbo.AgentJobs_Get", false, 120, "@InstanceID", null, null),
        new("Jobs & SQL Agent", "Running jobs", "dbo.RunningJobs_Get", false, 60, "@InstanceID", null, null),
        new("Jobs & SQL Agent", "Job stats", "dbo.JobStats_Get", false, 120, "@InstanceID", null, null),
        new("Jobs & SQL Agent", "Job stats summary", "dbo.JobStatsSummary_Get", false, 120, "@InstanceID", null, null),
        new("Jobs & SQL Agent", "Job timeline", "dbo.JobTimeline_Get", false, 120, "@InstanceID", null, null),
        new("Jobs & SQL Agent", "Job categories", "dbo.JobCategories_Get", false, 60, "@InstanceID", null, null),
        new("Jobs & SQL Agent", "Job steps", "dbo.JobSteps_Get", false, 120, "@InstanceID", null, "Usually needs JobID in JSON."),
        new("Jobs & SQL Agent", "Job step", "dbo.JobStep_Get", false, 60, "@InstanceID", null, "Needs JobID / StepID in JSON."),
        new("Jobs & SQL Agent", "Job DDL history", "dbo.JobDDLHistory_Get", false, 120, "@InstanceID", null, null),
        new("Jobs & SQL Agent", "Job diff", "dbo.Job_Diff", false, 120, "@InstanceID", null, "Pass job keys in JSON per GUI."),
        new("Storage & backups", "Drives", "dbo.Drives_Get", false, 120, "@InstanceID", null, null),
        new("Storage & backups", "Drive snapshots / history", "dbo.DriveSnapshot_Get", false, 120, "@InstanceID", null, null),
        new("Storage & backups", "DB files", "dbo.DBFiles_Get", false, 120, "@InstanceID", "@DatabaseID", null),
        new("Storage & backups", "File groups", "dbo.FileGroup_Get", false, 120, "@InstanceID", "@DatabaseID", null),
        new("Storage & backups", "DB space (tracking)", "dbo.DBSpace_Get", false, 180, "@InstanceID", "@DatabaseID", null),
        new("Storage & backups", "DB file snapshots", "dbo.DBFileSnapshot_Get", false, 180, "@InstanceID", "@DatabaseID", null),
        new("Storage & backups", "Backup summary", "dbo.BackupSummary_Get", false, 120, "@InstanceID", null, null),
        new("Storage & backups", "TempDB config", "dbo.TempDBConfig_Get", false, 120, "@InstanceID", null, null),
        new("HA / DR", "Availability Groups summary", "dbo.AvailabilityGroupSummary_Get", false, 120, "@InstanceID", null, null),
        new("HA / DR", "Log shipping summary", "dbo.LogShippingSummary_Get", false, 120, "@InstanceID", null, null),
        new("HA / DR", "Log shipping detail", "dbo.LogShipping_Get", false, 120, "@InstanceID", null, null),
        new("HA / DR", "Database mirroring summary", "dbo.DatabaseMirroringSummary_Get", false, 120, "@InstanceID", null, null),
        new("HA / DR", "Database mirroring detail", "dbo.DatabaseMirroring_Get", false, 120, "@InstanceID", null, null),
        new("Configuration & patching", "Instance info", "dbo.InstanceInfo_Get", false, 60, "@InstanceID", null, null),
        new("Configuration & patching", "Server configuration", "dbo.Configuration_Get", false, 120, "@InstanceID", null, null),
        new("Configuration & patching", "Sys config history", "dbo.SysConfigHistory_Get", false, 120, "@InstanceID", null, null),
        new("Configuration & patching", "SQL patching", "dbo.SQLPatching_Get", false, 120, "@InstanceID", null, null),
        new("Configuration & patching", "Build reference", "dbo.BuildReference_Get", false, 60, "@InstanceID", null, null),
        new("Configuration & patching", "Hardware", "dbo.Hardware_Get", false, 120, "@InstanceID", null, null),
        new("Configuration & patching", "Host upgrade history", "dbo.HostUpgradeHistory_Get", false, 120, "@InstanceID", null, null),
        new("Configuration & patching", "Drivers", "dbo.Drivers_Get", false, 120, "@InstanceID", null, null),
        new("Configuration & patching", "Trace flags", "dbo.TraceFlags_Get", false, 120, "@InstanceID", null, null),
        new("Configuration & patching", "Trace flag history", "dbo.TraceFlagHistory_Get", false, 120, "@InstanceID", null, null),
        new("Configuration & patching", "SQL Agent alerts config", "dbo.AlertsConfig_Get", false, 120, "@InstanceID", null, null),
        new("Configuration & patching", "SQL Agent alerts", "dbo.Alerts_Get", false, 120, "@InstanceID", null, null),
        new("Databases", "Databases by instance", "dbo.DatabasesByInstance_Get", false, 120, "@InstanceID", null, null),
        new("Databases", "Databases — all info", "dbo.DatabasesAllInfo_Get", false, 180, "@InstanceID", null, null),
        new("Databases", "DB summary", "dbo.DBSummary_Get", false, 120, "@InstanceID", "@DatabaseID", null),
        new("Databases", "DB options history", "dbo.DBOptionsHistory_Get", false, 120, "@InstanceID", "@DatabaseID", null),
        new("Databases", "DB configuration", "dbo.DBConfiguration_Get", false, 120, "@InstanceID", "@DatabaseID", null),
        new("Databases", "DB configuration history", "dbo.DBConfigurationHistory_Get", false, 120, "@InstanceID", "@DatabaseID", null),
        new("DDL & schema", "Database finder", "dbo.DatabaseFinder_Get", false, 120, null, null, "Add filters in JSON as in GUI."),
        new("DDL & schema", "DB objects", "dbo.DBObjects_Get", false, 120, "@InstanceID", "@DatabaseID", null),
        new("DDL & schema", "DDL for object", "dbo.DDL_Get", false, 120, "@InstanceID", null, "Needs object keys in JSON."),
        new("DDL & schema", "DDL history for object", "dbo.DDLHistoryForObject_Get", false, 120, "@InstanceID", null, null),
        new("DDL & schema", "Object types", "dbo.ObjectType_Get", false, 60, null, null, null),
        new("DDL & schema", "DDL snapshots", "dbo.DDLSnapshots_Get", false, 120, "@InstanceID", "@DatabaseID", null),
        new("DDL & schema", "DDL snapshot diff", "dbo.DDLSnapshotDiff_Get", false, 180, "@InstanceID", null, null),
        new("DDL & schema", "DDL snapshot instance summary", "dbo.DDLSnapshotInstanceSummary_Get", false, 120, "@InstanceID", null, null),
        new("DDL & schema", "DDL snapshot dates", "dbo.DDLSnapshotDates_Get", false, 120, "@InstanceID", "@DatabaseID", null),
        new("DDL & schema", "Database DDL compare", "dbo.DatabaseDDLCompare_Get", false, 300, "@InstanceID", null, null),
        new("DDL & schema", "DB schema at date", "dbo.DBSchemaAtDate_Get", false, 300, "@InstanceID", null, null),
        new("DDL & schema", "Instances with DDL snapshot", "dbo.InstancesWithDDLSnapshot_Get", false, 60, null, null, null),
        new("DDL & schema", "Databases with DDL snapshot", "dbo.DatabasesWithDDLSnapshot_Get", false, 60, "@InstanceID", null, null),
        new("Custom & tools", "Custom checks", "dbo.CustomCheck_Get", false, 120, "@InstanceID", null, null),
        new("Custom & tools", "Custom check context", "dbo.CustomCheckContext_Get", false, 120, "@InstanceID", null, null),
        new("Custom & tools", "Custom check test", "dbo.CustomCheckTest_Get", false, 120, "@InstanceID", null, null),
        new("Custom & tools", "Custom checks history", "dbo.CustomChecksHistory_Get", false, 120, "@InstanceID", null, null),
        new("Custom & tools", "Custom tools", "dbo.CustomTools_Get", false, 60, null, null, null),
        new("Custom & tools", "Custom report definition", "dbo.CustomReport_Get", false, 120, null, null, "Pass ReportID etc. in JSON."),
        new("Custom & tools", "Performance counters (pick list)", "dbo.Counters_Get", false, 120, "@InstanceID", null, null),
        new("Tags & reports", "Tag report", "dbo.TagReport_Get", false, 120, null, null, "Parameters depend on report; use JSON."),
        new("Repository options", "Data retention settings", "dbo.DataRetention_Get", false, 60, null, null, null),
    ];

    public sealed record MutatingEntry(string Category, string Label, string Procedure, int SuggestedTimeoutSeconds, string? Notes);

    /// <summary>Shown only when Repository:AllowMutatingStoredProcedures is true.</summary>
    public static readonly MutatingEntry[] MutatingEntries =
    [
        new("Ack / clear", "Acknowledge instance uptime", "dbo.InstanceUptimeAck", 60, null),
        new("Ack / clear", "Acknowledge corruption", "dbo.Corruption_Ack", 60, null),
        new("Ack / clear", "Acknowledge collection errors", "dbo.AcknowledgeErrors", 60, null),
        new("Ack / clear", "Acknowledge memory dumps", "dbo.AcknowledgeMemoryDumps", 60, null),
        new("Plan forcing", "Plan forcing log — add", "dbo.PlanForcingLog_Add", 60, null),
        new("Plan forcing", "Plan forcing log — update", "dbo.PlanForcingLog_Upd", 60, null),
        new("Tags", "Instance tag — add", "dbo.InstanceTags_Add", 60, null),
        new("Tags", "Instance tag — delete", "dbo.InstanceTags_Del", 60, null),
        new("Alerts & thresholds", "Alert thresholds update", "dbo.AlertThresholds_Upd", 60, null),
        new("Alerts & thresholds", "DB file thresholds update", "dbo.DBFileThresholds_Upd", 60, null),
        new("Alerts & thresholds", "Instance uptime thresholds update", "dbo.InstanceUptimeThresholds_Upd", 60, null),
        new("Alerts & thresholds", "Memory dump thresholds update", "dbo.MemoryDumpThresholds_Upd", 60, null),
        new("Alerts & thresholds", "Backup thresholds update", "dbo.BackupThresholds_Upd", 60, null),
        new("OS modules", "OS loaded module status — delete", "dbo.OSLoadedModulesStatus_Del", 60, null),
        new("OS modules", "OS loaded module status — add", "dbo.OSLoadedModulesStatus_Add", 60, null),
        new("OS modules", "OS loaded module status — update", "dbo.OSLoadedModulesStatus_Upd", 60, null),
        new("OS modules", "OS loaded modules — refresh status", "dbo.OSLoadedModules_RefreshStatus", 120, null),
        new("Reports", "Custom report — update", "dbo.CustomReport_Upd", 60, null),
    ];
}
