/** DBA Dash Summary_Get status columns — DBADashStatusEnum: Critical=1, Warning=2, N/A=3, OK=4, Acknowledged=5 */
export const SUMMARY_STATUS_KEYS: { key: string; label: string }[] = [
  { key: 'FullBackupStatus', label: 'Backup FULL' },
  { key: 'DiffBackupStatus', label: 'Backup DIFF' },
  { key: 'LogBackupStatus', label: 'Backup LOG' },
  { key: 'LogShippingStatus', label: 'Log Shipping' },
  { key: 'DriveStatus', label: 'Drive Space' },
  { key: 'FileFreeSpaceStatus', label: 'File Space' },
  { key: 'LogFreeSpaceStatus', label: 'Log Space' },
  { key: 'JobStatus', label: 'Agent Jobs' },
  { key: 'AGStatus', label: 'Availability Groups' },
  { key: 'CorruptionStatus', label: 'Corruption' },
  { key: 'LastGoodCheckDBStatus', label: 'Last Good Check DB' },
  { key: 'MemoryDumpStatus', label: 'Memory Dump' },
  { key: 'SnapshotAgeStatus', label: 'Snapshot Age' },
  { key: 'UptimeStatus', label: 'Instance Uptime' },
  { key: 'IsAgentRunningStatus', label: 'Is Agent Running' },
  { key: 'DBMailStatus', label: 'DB Mail' },
  { key: 'QueryStoreStatus', label: 'Query Store' },
  { key: 'AlertStatus', label: 'SQL Agent Alerts' },
  { key: 'PctMaxSizeStatus', label: '% Max Size' },
  { key: 'CollectionErrorStatus', label: 'DBA Dash Errors (24hrs)' },
  { key: 'DatabaseStateStatus', label: 'Database State' },
  { key: 'IdentityStatus', label: 'Identity Columns' },
  { key: 'CustomCheckStatus', label: 'Custom Check' },
  { key: 'MirroringStatus', label: 'Mirroring' },
  { key: 'ElasticPoolStorageStatus', label: 'Elastic Pool Storage' },
];
